spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters: #https://cloud.spring.io/spring-cloud-gateway/reference/html/
            - RewritePath=/user-service/, /
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-cluster-8761:8761/eureka/, http://eureka-cluster-8762:8762/eureka/
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    hostname: api-gateway

server:
  port: 8800
logging:
  level:
    root: debug

